### ISSUE TITLE
Add debug table

### ISSUE THREAD

**Issue by bigPapiTech** [bigPapiTech/slimThim#11]

**Comment by CarCarGoes** [comment]
Sorry @bigPapiTech ! I went offline for a week but I'm back and eager to help.... I'm a complete newbie so it may be slow for me to figure out 😬

**Comment by bigPapiTech** [comment]
ah no problem. I'm a noob as well just trying to learn this stuff  🙂
________________________________
Från: CarCarGoes ***@***.***>
Skickat: den 1 mars 2023 20:39
Till: bigPapiTech/slimThim ***@***.***>
Kopia: bigPapiTech ***@***.***>; Mention ***@***.***>
Ämne: Re: [bigPapiTech/slimThim] Add debug table (Issue #11)


Sorry @bigPapiTech<https://github.com/bigPapiTech> ! I went offline for a week but I'm back and eager to help.... I'm a complete newbie so it may be slow for me to figure out 😬

**Comment by CarCarGoes** [comment]
@bigPapiTech Idk code, I'm an aspiring tech writer. please lmk how else I may contribute
